# Generated by Django 4.1.5 on 2023-01-23 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_title_created_title_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='user',
        ),
        migrations.RemoveField(
            model_name='title',
            name='user',
        ),
    ]
