# Generated by Django 4.1.5 on 2023-01-23 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_author_user_remove_title_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.AlterModelOptions(
            name='title',
            options={'ordering': ['-updated', '-created']},
        ),
    ]
