# Generated by Django 4.1.5 on 2023-01-22 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_curiositie_curiosity_author_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='curiosity',
            new_name='about',
        ),
        migrations.RemoveField(
            model_name='author',
            name='description',
        ),
    ]
