# Generated by Django 4.1.5 on 2023-02-02 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_comment_options_alter_title_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.RenameField(
            model_name='author',
            old_name='author',
            new_name='authors',
        ),
    ]
