# Generated by Django 4.1.5 on 2023-02-02 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_author_options_rename_author_author_authors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='authors',
            new_name='author',
        ),
    ]
