# Generated by Django 4.1.5 on 2023-01-22 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_rename_name_curiosity_curiosity_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='title',
            field=models.ForeignKey(default='Unknown', null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.title'),
        ),
        migrations.AddField(
            model_name='title',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.RemoveField(
            model_name='title',
            name='curiosity',
        ),
        migrations.DeleteModel(
            name='Curiosity',
        ),
        migrations.AddField(
            model_name='title',
            name='curiosity',
            field=models.TextField(blank=True, null=True),
        ),
    ]
