# Generated by Django 4.1.5 on 2023-01-22 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_comment_title_title_updated_remove_title_curiosity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.title'),
        ),
    ]
