# Generated by Django 4.1.5 on 2023-02-05 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_band_message_rhythm_remove_comment_author_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='music',
            new_name='band',
        ),
    ]
