# Generated by Django 4.1.5 on 2023-02-05 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_band_music'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='music',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
