# Generated by Django 4.1.5 on 2023-02-05 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_remove_band_music_music'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='youtubelink',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
