# Generated by Django 4.1.5 on 2023-01-22 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_comment_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='title',
        ),
    ]
