# Generated by Django 4.1.5 on 2023-01-22 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_comment_title_alter_comment_author_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
